### ISSUE TITLE
Typekit fonts not loading

### ISSUE THREAD

**Issue by sebastiansandqvist** [vhx/quartz-react#4]
The brandon font is loaded with typekit on https://vhx.quartz.tv, but cannot currently be loaded in this repo's demo. The following error is displayed:

```
mee1sll.js:35 Typekit: the domain "localhost" isn't in the list of published domains for kit "mee1sll".
```

It is possible that the kit settings disallow `localhost` altogether. If that is the case, as long as the domain that these components are used on is added to the kit's whitelist the fonts should load correctly.

**Comment by davegonzalez** [comment]
Will talk to Don about having a potential fallback for non-vhx usage.
